/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as ProjectsVehicleIdCardboardRouteImport } from './routes/projects_.$vehicleId.cardboard'
import { Route as VehiclesVehicleIdIndexRouteImport } from './routes/vehicles.$vehicleId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVehicleIdCardboardRoute =
  ProjectsVehicleIdCardboardRouteImport.update({
    id: '/projects_/$vehicleId/cardboard',
    path: '/projects/$vehicleId/cardboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const VehiclesVehicleIdIndexRoute = VehiclesVehicleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesVehicleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/service': typeof ServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/projects/$vehicleId/cardboard': typeof ProjectsVehicleIdCardboardRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/service': typeof ServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/projects/$vehicleId/cardboard': typeof ProjectsVehicleIdCardboardRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/service': typeof ServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRouteWithChildren
  '/projects_/$vehicleId/cardboard': typeof ProjectsVehicleIdCardboardRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/service'
    | '/api/health'
    | '/vehicles/$vehicleId'
    | '/projects/$vehicleId/cardboard'
    | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/service'
    | '/api/health'
    | '/projects/$vehicleId/cardboard'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/service'
    | '/api/health'
    | '/vehicles/$vehicleId'
    | '/projects_/$vehicleId/cardboard'
    | '/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ServiceRoute: typeof ServiceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRouteWithChildren
  ProjectsVehicleIdCardboardRoute: typeof ProjectsVehicleIdCardboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$vehicleId/cardboard': {
      id: '/projects_/$vehicleId/cardboard'
      path: '/projects/$vehicleId/cardboard'
      fullPath: '/projects/$vehicleId/cardboard'
      preLoaderRoute: typeof ProjectsVehicleIdCardboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId/': {
      id: '/vehicles/$vehicleId/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof VehiclesVehicleIdIndexRouteImport
      parentRoute: typeof VehiclesVehicleIdRoute
    }
  }
}

interface VehiclesVehicleIdRouteChildren {
  VehiclesVehicleIdIndexRoute: typeof VehiclesVehicleIdIndexRoute
}

const VehiclesVehicleIdRouteChildren: VehiclesVehicleIdRouteChildren = {
  VehiclesVehicleIdIndexRoute: VehiclesVehicleIdIndexRoute,
}

const VehiclesVehicleIdRouteWithChildren =
  VehiclesVehicleIdRoute._addFileChildren(VehiclesVehicleIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ServiceRoute: ServiceRoute,
  ApiHealthRoute: ApiHealthRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRouteWithChildren,
  ProjectsVehicleIdCardboardRoute: ProjectsVehicleIdCardboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
